import java.sql.*;
 import javax.swing.*;
import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
public class update extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
  static String f1,f2,s1,add,add1,add2,add3,add4;
  String filename;
    public update(String s1) {
       con=Connecter.ConnectDB();
       this.f2=s1;
       
      
       initComponents();
       txtusername.setText(s1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtmno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        image1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 170, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 102));
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 220, 100, 30);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 102));
        jLabel4.setText("Mobile No");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 260, 110, 28);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 102));
        jLabel5.setText("Address");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 300, 100, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 102));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 350, 90, 30);
        jPanel2.add(txtfname);
        txtfname.setBounds(130, 170, 140, 30);
        jPanel2.add(txtlname);
        txtlname.setBounds(130, 220, 140, 30);
        jPanel2.add(txtmno);
        txtmno.setBounds(130, 260, 140, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thin-gray-edit-profile-button-hi.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 10, 550, 100);
        jPanel2.add(txtaddress);
        txtaddress.setBounds(130, 310, 140, 30);
        jPanel2.add(txtpassword);
        txtpassword.setBounds(130, 350, 140, 30);

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 102));
        jLabel8.setText("Username");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 130, 100, 30);
        jPanel2.add(txtusername);
        txtusername.setBounds(130, 130, 140, 30);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (3).jpg"))); // NOI18N

        jDesktopPane1.setLayer(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel2.add(jDesktopPane1);
        jDesktopPane1.setBounds(340, 120, 220, 190);
        jPanel2.add(path);
        path.setBounds(420, 330, 160, 20);

        image1.setBackground(new java.awt.Color(0, 255, 0));
        image1.setText("Attach Image");
        image1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image1ActionPerformed(evt);
            }
        });
        jPanel2.add(image1);
        image1.setBounds(310, 320, 100, 30);

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update-Button.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateKeyTyped(evt);
            }
        });
        jPanel2.add(update);
        update.setBounds(10, 390, 170, 60);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (1).jpg"))); // NOI18N
        save.setText("jButton1");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(220, 390, 130, 60);

        jButton2.setBackground(new java.awt.Color(153, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button-delete.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(380, 393, 170, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editing-compressed.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-10, 0, 610, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       con=Connecter.ConnectDB();
     String sql1="update sample set f_name='"+txtfname.getText()+"',l_name='"+txtlname.getText()+"',m_no='"+txtmno.getText()+"', address='"+txtaddress.getText()+"', password='"+txtpassword.getText()+"' where username Like '%"+txtusername.getText()+"%'";
       String sql="update sample set f_name='"+txtfname.getText()+"',l_name='"+txtlname.getText()+"',m_no='"+txtmno.getText()+"', address='"+txtaddress.getText()+"', password='"+txtpassword.getText()+"',image=? where username Like '%"+txtusername.getText()+"%'";
      try{
          if(path.getText().isEmpty())
          pst=con.prepareStatement(sql1);
          else 
          { pst=con.prepareStatement(sql);
          
          
           pst.setBytes(1,person_image);
          this.setVisible(true);}
          pst.execute();
          JOptionPane.showMessageDialog(null,"PROFILE EDITED SUCCESSFULLY");
          this.setVisible(false);
          search k=new search();
          k.setVisible(true);
          
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       con=Connecter.ConnectDB();
       String sql1="select * from sample where username Like '%"+txtusername.getText()+"%'";
       try{
           pst=con.prepareStatement(sql1);
           rs=pst.executeQuery();
           if(rs.next()){
           String add=rs.getString("f_name");
           txtfname.setText(add);
            String add1=rs.getString("l_name");
           txtlname.setText(add1);
            String add4=rs.getString("m_no");
           txtmno.setText(add4);
            String add2=rs.getString("address");
           txtaddress.setText(add2);
            String add3=rs.getString("password");
           txtpassword.setText(add3);
          byte[]imagedata=rs.getBytes("image");
           format=new ImageIcon(imagedata);
           image.setIcon(format);
           }
       }
       catch(Exception e)
       {
          e.printStackTrace();
           // JOptionPane.showMessageDialog(null,e);
       } 
    }//GEN-LAST:event_updateActionPerformed

    private void updateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateKeyTyped
       
    }//GEN-LAST:event_updateKeyTyped

    private void image1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image1ActionPerformed
      JFileChooser chooser=new JFileChooser();
     chooser.showOpenDialog(null);
     File f=chooser.getSelectedFile();
      filename=f.getAbsolutePath();
     path.setText(filename);
     try{
     File image=new File(filename);
     FileInputStream fis=new FileInputStream(image);
     ByteArrayOutputStream bos=new ByteArrayOutputStream();
     byte[]buf=new byte[1024];
     for(int readNum;(readNum=fis.read(buf))!=-1; )
     {
         bos.write(buf,0,readNum);
     }
      person_image=bos.toByteArray();
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null, e);
     }
    
     
    }//GEN-LAST:event_image1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int p=JOptionPane.showConfirmDialog(null,"DO YOU REALLY WANT TO DELETE?","DELETE",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        String sql="delete from sample where username=?";
        try{
        pst=con.prepareStatement(sql);
        pst.setString(1,txtusername.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null,"DELETED SUCCESSFULLY");
        this.setVisible(false);
        Homepage1 q=new Homepage1();
        q.setVisible(true);
        
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update(f1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton image1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField path;
    private javax.swing.JButton save;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmno;
    private javax.swing.JTextField txtpassword;
    public static javax.swing.JTextField txtusername;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
private ImageIcon format=null;
int s=0;
byte[]person_image=null;
}
